cargo-features = ["edition"]

[package]
name = "json-pubsub"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.1", features = ["unstable"] }
serde = "1.0"
serde_derive = "1.0"
rmp = "0.8"
rmp-serde = "0.14"
rmpv = "0.4"
rand = "0.7"
error-chain = "0.12"
uuid = { version = "0.8", features = ["v4", "serde"] }
lazy_static = "1.4"
immutable-chunkmap = "0.5"
