[package]
name = "netidx"
version = "0.2.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Cross platform secure messaging framework, \"like DNS for values\""
homepage = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["network", "networking", "distributed", "kerberos"]
categories = ["network-programming"]

[target.'cfg(unix)'.dependencies]
libgssapi = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3",  features = ["sspi", "winnt", "impl-default", "winerror", "winbase", "sysinfoapi", "timezoneapi", "ntsecapi"] }

[dependencies]
log = "0.4"
anyhow = "1"
fxhash = "0.2"
futures = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "tcp", "time", "sync", "blocking", "stream", "io-util"] }
serde = { version = "1.0" }
serde_derive = "1"
serde_json = "1"
rand = "0.7"
lazy_static = "1"
bytes = "0.5"
byteorder = "1"
pin-utils = "0.1"
crossbeam = "0.7"
parking_lot = "0.10"
bitflags = "1"
arc-swap = "0.4"
get_if_addrs = "0.5"
base64 = "0.12"
dirs = "2"
sha3 = "0.8"
digest = "0.8"

[dev-dependencies]
proptest = "0.9"
