[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[profile.dev]
opt-level = "z"
lto = "thin"
debug = 1

[workspace]
members = [
    "netidx-core",
    "netidx-netproto",
    "netidx",
    "netidx-archive",
    "netidx-bscript",
    "netidx-protocols",
    "netidx-tools",
    "netidx-browser",
    "netidx-container"
]
