[package]
name = "json-pubsub"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2"
futures = "0.3"
async-std = { version = "1.1", features = ["unstable"] }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
futures_codec = "0.3"
rmp = "0.8"
rmpv = "0.4"
rmp-serde = "0.14"
rand = "0.7"
error-chain = "0.12"
uuid = { version = "0.8", features = ["v4", "serde"] }
lazy_static = "1.4"
bytes = "0.4"
