[package]
name = "netidx"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "it's like DNS for values"
homepage = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["network", "networking", "framework", "distributed", "kerberos", "krb5"]
categories = ["network-programming"]

[target.'cfg(unix)'.dependencies]
libgssapi = "0.4"
nix = "0.17"

[target.'cfg(windows)'.dependencies]
winapi = "0.3"

[dependencies]
log = "0.4"
anyhow = "1"
fxhash = "0.2"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0" }
serde_derive = "1"
serde_json = "1"
rand = "0.7"
lazy_static = "1"
bytes = "0.5"
byteorder = "1"
pin-utils = "0.1.0-alpha.4"
crossbeam = "0.7"
parking_lot = "0.10"
bitflags = "1"
arc-swap = "0.4"
trust-dns-resolver = "0.19"

[dev-dependencies]
proptest = "0.9"
