cargo-features = ["edition"]

[package]
name = "json-pubsub"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tokio = "0.1"
tokio-io = "0.1"
tokio-timer = "0.2"
tokio-async-await = "0.1"
futures = "0.1"
#futures-await = "0.1"
rand = "0.4"
error-chain = "0.11"
uuid = { version = "0.6", features = ["v4", "serde"] }
arccstr = { version = "1.2", features = ["serde"] }
immutable-chunkmap = "0.5"
lazy_static = "1.0"

[dev-dependencies]
tokio-timer = "0.2"
