cargo-features = ["edition"]

[package]
name = "json-pubsub"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-arccell = "0.6"
futures = "0.3"
async-std = { version = "1.1", features = ["unstable"] }
serde = "1.0"
serde_derive = "1.0"
serde_cbor = "0.10"
futures_codec = "0.3"
futures_cbor_codec = "0.1"
rand = "0.7"
error-chain = "0.12"
uuid = { version = "0.8", features = ["v4", "serde"] }
lazy_static = "1.4"
immutable-chunkmap = "0.5"
