[package]
name = "netidx-netproto"
version = "0.8.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "netidx wire protocol"
documentation = "https://docs.rs/netidx-netproto"
readme = "../README.md"
license = "MIT"

[dependencies]
netidx-core = { version = "0.7", path = "../netidx-core" }
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1"
globset = "0.4"
fxhash = "0.2"
lazy_static = "1"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
base64 = "0.13"
arcstr = { version = "1", features = ["serde"] }

[dev-dependencies]
proptest = "1"
