[package]
name = "netidx-netproto"
version = "0.16.4"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "netidx wire protocol"
documentation = "https://docs.rs/netidx-netproto"
readme = "../README.md"
license = "MIT"

[dependencies]
combine = "4"
netidx-core = { version = "^0.16", path = "../netidx-core" }
netidx-derive = { version = "0.16", path = "../netidx-derive" }
bytes = { version = "1", features = ["serde"] }
chrono = { version = "^0.4.23", features = ["serde"] }
anyhow = "1"
globset = "0.4"
fxhash = "0.2"
lazy_static = "1"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
base64 = "0.21"
arcstr = { version = "1", features = ["serde"] }
smallvec = { version = "1", features = ["const_generics", "union"] }
enumflags2 = "0.7"
indexmap = "1"
rust_decimal = { version = "1",  features = ["serde-with-float", "serde-with-str", "serde-with-arbitrary-precision"] }

[dev-dependencies]
proptest = "1"
