[package]
name = "netidx"
version = "0.6.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Cross platform secure messaging framework, \"like DNS for values\""
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["network", "networking", "distributed", "kerberos"]
categories = ["network-programming"]

[features]
default = ["krb5_iov"]
krb5_iov = ["libgssapi/iov"]

[target.'cfg(unix)'.dependencies]
libgssapi = { version = "0.4", path = "../../libgssapi/libgssapi", default_features = false }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3",  features = ["sspi", "winnt", "impl-default", "winerror", "winbase", "sysinfoapi", "timezoneapi", "ntsecapi"] }

[dependencies]
netidx-core = { version = "0.6", path = "../netidx-core" }
netidx-netproto = { version = "0.6", path = "../netidx-netproto" }
log = "0.4"
anyhow = "1"
fxhash = "0.2"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "io-util"] }
immutable-chunkmap = "0.5"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
rand = "0.8"
lazy_static = "1"
bytes = { version = "1", features = ["serde"] }
byteorder = "1"
crossbeam = "0.8"
parking_lot = "0.11"
bitflags = "1"
get_if_addrs = "0.5"
dirs = "3"
num_cpus = "1"

[dev-dependencies]
proptest = "0.10"
