[package]
name = "netidx"
version = "0.16.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Secure, fast, pub/sub messaging"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
readme = "../README.md"
keywords = ["network", "networking", "distributed", "kerberos"]
categories = ["network-programming"]

[features]
default = ["krb5_iov"]
krb5_iov = ["cross-krb5/iov"]

[dependencies]
netidx-core = { version = "^0.16", path = "../netidx-core" }
netidx-netproto = { version = "^0.16", path = "../netidx-netproto" }
cross-krb5 = { version = "0.3", default_features = false }
log = "0.4"
anyhow = "1"
fxhash = "0.2"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util", "fs"] }
immutable-chunkmap = "1"
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
rand = "0.8"
lazy_static = "1"
bytes = { version = "1", features = ["serde"] }
byteorder = "1"
crossbeam = "0.8"
parking_lot = "0.12"
bitflags = "1"
get_if_addrs = "0.5"
dirs = "4"
num_cpus = "1"
triomphe = "0.1"
arcstr = { version = "1", features = ["serde"] }
rustls-pemfile = "1"
rustls = "0.20"
tokio-rustls = "0.23"
webpki = "0.22"
x509-parser = "0.14"
pkcs8 = { version = "0.9", features = ["pem", "encryption"] }
keyring = "1"
