[package]
name = "netidx"
version = "0.10.4"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Secure, fast, pub/sub messaging"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
readme = "../README.md"
keywords = ["network", "networking", "distributed", "kerberos"]
categories = ["network-programming"]

[features]
default = ["krb5_iov"]
krb5_iov = ["cross-krb5/iov"]

[dependencies]
netidx-core = { version = "0.10", path = "../netidx-core" }
netidx-netproto = { version = "0.10", path = "../netidx-netproto" }
cross-krb5 = { version = "0.1", path = "../../cross-krb5", default_features = false }
log = "0.4"
anyhow = "1"
fxhash = "0.2"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util"] }
immutable-chunkmap = "1"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
rand = "0.8"
lazy_static = "1"
bytes = { version = "1", features = ["serde"] }
byteorder = "1"
crossbeam = "0.8"
parking_lot = "0.11"
bitflags = "1"
get_if_addrs = "0.5"
dirs = "3"
num_cpus = "1"
triomphe = "0.1"
