[package]
name = "netidx-bscript"
version = "0.10.4"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "An incremental scripting language for netidx"
documentation = "https://docs.rs/netidx-bscript"
readme = "../README.md"
license = "MIT"

[dependencies]
anyhow = "1"
base64 = "0.13"
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
combine = "4"
fxhash = "0.2"
lazy_static = "1"
netidx-netproto = { path = "../netidx-netproto", version = "^0.10.1" }
netidx-core = { path = "../netidx-core", version = "0.10" }
netidx = { path = "../netidx", version = "0.10" }
regex = "1"
serde = "1"
serde_derive = "1"

[dev-dependencies]
proptest = "1"
