[package]
name = "netidx-bscript"
version = "0.17.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "An incremental scripting language for netidx"
documentation = "https://docs.rs/netidx-bscript"
readme = "../README.md"
license = "MIT"

[features]
default = []
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
base64 = "0.21"
bytes = "1"
chrono = { version = "^0.4.23", features = ["serde"] }
combine = "4"
fxhash = "0.2"
lazy_static = "1"
netidx-netproto = { path = "../netidx-netproto", version = "^0.17" }
netidx-core = { path = "../netidx-core", version = "^0.17" }
netidx = { path = "../netidx", version = "^0.17", default_features = false }
regex = "1"
serde = "1"
serde_derive = "1"
arcstr = { version = "1", features = ["serde"] }

[dev-dependencies]
proptest = "1"
