[package]
name = "netidx-archive"
version = "0.10.4"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "netidx archive file format"
documentation = "https://docs.rs/netidx-archive"
readme = "../README.md"
license = "MIT"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
netidx = { path = "../netidx", version = "0.10", default_features = false }
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util"] }
bytes = "1"
fs3 = "0.5"
mapr = "0.8"
fxhash = "0.2"
lazy_static = "1"
packed_struct = "0.5"
packed_struct_codegen = "0.5"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4"
parking_lot = "0.11"
indexmap = "1"
diligent-date-parser = "0.1"
