[package]
name = "netidx-archive"
version = "0.18.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "netidx archive file format"
documentation = "https://docs.rs/netidx-archive"
readme = "../README.md"
license = "MIT"

[features]
default = []
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
netidx = { path = "../netidx", version = "^0.17", default_features = false }
netidx-protocols = { path = "../netidx-protocols", version = "^0.17", default_features = false }
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util", "process"] }
bytes = "1"
fs3 = "0.5"
memmap2 = "0.5"
fxhash = "0.2"
futures = "0.3"
arcstr = { version = "1", features = ["serde"] }
lazy_static = "1"
packed_struct = "0.10"
packed_struct_codegen = "0.10"
chrono = { version = "^0.4.23", features = ["serde"] }
log = "0.4"
parking_lot = "0.12"
indexmap = "1"
diligent-date-parser = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
