[package]
name = "netidx-container"
version = "0.15.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
license = "MIT"
description = "netidx embeddable database"
homepage = "https://netidx.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
readme = "../README.md"
documentation = "https://docs.rs/netidx-container"
keywords = ["networking", "distributed", "kerberos", "database"]
categories = ["network-programming"]

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
base64 = "0.20"
bytes = "1"
chrono = { version = "^0.4.23" }
futures = "0.3"
fxhash = "0.2"
log = "0.4"
netidx-core = { path = "../netidx-core", version = "^0.15" }
netidx = { path = "../netidx", version = "^0.15" , default_features = false }
netidx-protocols = { path = "../netidx-protocols", version = "^0.15", default_features = false }
netidx-bscript = { path = "../netidx-bscript", version = "^0.15", default_features = false }
parking_lot = "0.12"
serde = "1"
serde_derive = "1"
serde_json = "1"
sled = { version = "0.34", features = ["zstd", "compression"] }
structopt = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util", "fs", "parking_lot"] }
uuid = { version = "1", features = ["v4", "serde"] }
lazy_static = "1"
arcstr = { version = "1", features = ["serde"] }
rayon = "1"
dirs = "4"
