[package]
name = "netidx-browser"
version = "0.1.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A graphical browser/ui creator for netidx"
homepage = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["networking", "distributed", "kerberos", "tool"]
categories = ["gui"]

[[bin]]
name = "netidx-browser"
path = "src/main.rs"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[profile.dev]
opt-level = "z"
lto = "thin"
debug = 1

[target.'cfg(unix)'.dependencies]
daemonize = "0.4"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"
netidx = { path = "..", version = "0.4" , default_features = false }
netidx-protocols = { path = "../netidx-protocols", version = "0.3", default_features = false }
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
bytes = "0.5"
anyhow = "1"
log = "0.4"
env_logger = "0.7"
base64 = "0.12"
parking_lot = "0.11"
indexmap = "1"
once_cell = "1"
gtk = { version = "0.9", features = ["v3_24"] }
gio = "0.9"
glib = "0.10"
gdk = "0.13"
cairo-rs = "0.9"
plotters = { version = "0.3", default_features = false, features = ["datetime", "line_series", "ttf"] }
plotters-cairo = "0.3"
