[package]
name = "netidx-browser"
version = "0.11.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
license = "MIT"
description = "graphical browser for netidx directories"
homepage = "https://estokes.github.io/netidx-book/"
readme = "../README.md"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["networking", "distributed", "kerberos", "tool"]
categories = ["gui"]

[[bin]]
name = "netidx-browser"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
daemonize = "0.4"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "io-util"] }
serde = "1.0"
chrono = { version = "0.4", features = ["serde"] }
netidx-core = { path = "../netidx-core", version = "0.11" }
netidx-netproto = { path = "../netidx-netproto", version = "0.11" }
netidx = { path = "../netidx", version = "0.11" , default_features = false }
netidx-bscript = { path = "../netidx-bscript", version = "0.11", default_features = false }
netidx-protocols = { path = "../netidx-protocols", version = "0.11", default_features = false }
regex = "1"
serde_derive = "1.0"
serde_json = "1.0"
bytes = "1"
fxhash = "0.2"
anyhow = "1"
log = "0.4"
env_logger = "0.9"
base64 = "0.13"
parking_lot = "0.12"
indexmap = "1"
once_cell = "1"
gtk = { version = "0.15", features = ["v3_24"] }
pango = "0.15"
gio = "0.15"
glib = "0.15"
gdk = "0.15"
gdk-pixbuf = "0.15"
sourceview4 = { version = "0.3", path = "../../sourceview4-rs/sourceview4" }
plotters = { version = "0.3", default_features = false, features = ["datetime", "line_series", "ttf"] }
plotters-backend = "0.3"
lazy_static = "1"
arcstr = { version = "1", features = ["serde"] }
radix_trie = "0.2"
rand = "0.8"
dirs = "4"
