[package]
name = "netidx-core"
version = "0.16.10"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2021"
license = "MIT"
description = "netidx core libraries"
homepage = "https://netidx.github.io/netidx-book/"
readme = "../README.md"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["network", "networking", "distributed", "kerberos"]
categories = ["network-programming"]

[dependencies]
bytes = { version = "1", features = ["serde"] }
chrono = { version = "^0.4.23", features = ["serde"] }
crossbeam = "0.8"
futures = "0.3"
fxhash = "0.2"
anyhow = "1"
sha3 = "0.10"
digest = "0.10"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
pin-utils = "0.1"
arcstr = { version = "1", features = ["serde"] }
rust_decimal = { version = "1",  features = ["serde-with-float", "serde-with-str", "serde-with-arbitrary-precision"] }
uuid = "1"
smallvec = "1"
enumflags2 = "0.7"
