[package]
name = "netidx-core"
version = "0.6.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Cross platform secure messaging framework, core utilities"
homepage = "https://estokes.github.io/netidx-book/"
readme = "README.md"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["network", "networking", "distributed", "kerberos"]
categories = ["network-programming"]

[dependencies]
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
crossbeam = "0.8"
futures = "0.3"
fxhash = "0.2"
anyhow = "1"
rand = "0.8"
sha3 = "0.9"
digest = "0.9"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
pin-utils = "0.1"
