[package]
name = "netidx-tools"
version = "0.9.1"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "netidx command line tools"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
readme = "../README.md"
documentation = "https://docs.rs/netidx"
keywords = ["networking", "distributed", "kerberos", "tool"]
categories = ["network-programming"]

[[bin]]
name = "netidx"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
daemonize = "0.4"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
async-stream = "0.3"
base64 = "0.13"
bytes = "1"
chrono = { version = "0.4" }
env_logger = "0.8"
fs3 = "0.5"
futures = "0.3"
fxhash = "0.2"
indexmap = "1"
log = "0.4"
netidx-archive = { path = "../netidx-archive", version = "0.9", default_features = false }
netidx-core = { path = "../netidx-core", version = "0.9" }
netidx = { path = "../netidx", version = "0.9" , default_features = false }
netidx-protocols = { path = "../netidx-protocols", version = "0.9", default_features = false }
netidx-bscript = { path = "../netidx-bscript", version = "0.9" }
parking_lot = "0.11"
serde = "1"
serde_derive = "1"
serde_json = "1"
sled = { version = "0.34", features = ["zstd", "compression"] }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
lazy_static = "1"
arcstr = { version = "1", features = ["serde"] }
rayon = "1"
