[package]
name = "netidx-tools"
version = "0.3.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Cross platform secure messaging framework, \"like DNS for values\""
homepage = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["networking", "networking", "distributed", "kerberos", "tool"]
categories = ["network-programming"]

[[bin]]
name = "netidx"
path = "src/main.rs"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[profile.dev]
opt-level = "z"
lto = "thin"
debug = 1

[target.'cfg(target_os = "macos")'.dependencies]
daemonize = "0.4"
netidx = { path = ".." }

[target.'cfg(unix)'.dependencies]
daemonize = "0.4"
netidx = { path = "..", features = ["krb5_iov"] }

[target.'cfg(windows)'.dependencies]
netidx = { path = ".." }

[features]
default = []
browser = ["gtk/v3_24", "gio", "glib", "gdk"]

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
bytes = "0.5"
netidx-protocols = { path = "../netidx-protocols" }
anyhow = "1"
log = "0.4"
env_logger = "0.7"
base64 = "0.12"
parking_lot = "0.11"
indexmap = "1"
once_cell = "1"
gtk = { version = "0.9", features = ["v3_24"], optional = true }
gio = { version = "0.9", optional = true }
glib = { version = "0.10", optional = true }
gdk = { version = "0.13", optional = true }
