[package]
name = "netidx-tools"
version = "0.5.1"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Cross platform secure messaging framework, like DNS for values"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
documentation = "https://docs.rs/netidx"
keywords = ["networking", "distributed", "kerberos", "tool"]
categories = ["network-programming"]

[[bin]]
name = "netidx"
path = "src/main.rs"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[profile.dev]
opt-level = "z"
lto = "thin"
debug = 1

[target.'cfg(unix)'.dependencies]
daemonize = "0.4"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
futures = "0.3"
tokio = { version = "0.3", features = ["full"] }
serde = "1.0"
netidx = { path = "..", version = "0.5" , default_features = false }
serde_json = "1.0"
structopt = "0.3"
bytes = "0.6"
anyhow = "1"
log = "0.4"
env_logger = "0.8"
base64 = "0.13"
parking_lot = "0.11"
fs3 = "0.5"
mapr = "0.8"
uuid = { version = "0.8", features = ["v4"] }
diligent_date_parser = "0.1"
