[package]
name = "netidx-protocols"
version = "0.3.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
description = "Various protocols build on top of netidx"
license = "MIT"

[dependencies]
netidx = { path = ".." }
serde = "1"
serde_derive = "1"
