[package]
name = "netidx-protocols"
version = "0.5.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
homepage = "https://estokes.github.io/netidx-book/"
repository = "https://github.com/estokes/netidx"
description = "Various protocols build on top of netidx"
documentation = "https://docs.rs/netidx-protocols"
license = "MIT"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
netidx = { path = "..", version = "0.4", default_features = false }
serde = "1"
serde_derive = "1"
combine = "4"
base64 = "0.13"
bytes = "0.5"
