[package]
name = "netidx-protocols"
version = "0.4.0"
authors = ["Eric Stokes <letaris@gmail.com>"]
edition = "2018"
description = "Various protocols build on top of netidx"
license = "MIT"

[features]
default = ["krb5_iov"]
krb5_iov = ["netidx/krb5_iov"]

[dependencies]
anyhow = "1"
netidx = { path = "..", default_features = false }
serde = "1"
serde_derive = "1"
combine = "4"
base64 = "0.12"
bytes = "0.5"
